### ISSUE TITLE
Cleanup after the v2.0 launch

### ISSUE THREAD

**Issue by defuse** [defuse/encutil#1]
For example the `composer install` doesn't work yet because v2.0 hasn't launched, should probably add some comments explaining how to use the library as well.

**Comment by sstok** [comment]
FYI, http://symfony.com/doc/current/components/console/helpers/questionhelper.html#hiding-the-user-s-response or https://github.com/Seldaek/cli-prompt if you don't want to use a Symfony library.

**Comment by defuse** [comment]
Done. Thanks @sstok!
